CC=gcc

all: prim kruskal lcs

prim : prim.c
		$(CC) -o prim.out prim.c
		
kruskal : kruskal.c
		$(CC) -o kruskal.out kruskal.c
		
lcs : lcs.c
		$(CC) -o lcs.out lcs.c
		
clean: 
	rm prim.out kruskal.out lcs.out