sachdeva_pa2_stra.exe sachdeva_pa2_tro.exe sachdeva_pa2_floyd.exe:sachdeva_pa2_stra.o sachdeva_pa2_tro.o sachdeva_pa2_floyd.o
	gcc sachdeva_pa2_stra.o -o sachdeva_pa2_stra.exe
	gcc sachdeva_pa2_tro.o -o sachdeva_pa2_tro.exe
	gcc sachdeva_pa2_floyd.o -o sachdeva_pa2_floyd.exe
	
sachdeva_pa2_stra.o:sachdeva_pa2_stra.c
	gcc -c sachdeva_pa2_stra.c
sachdeva_pa2_tro.o:sachdeva_pa2_tro.c
	gcc -c sachdeva_pa2_tro.c
sachdeva_pa2_floyd.o:sachdeva_pa2_floyd.c
	gcc -c sachdeva_pa2_floyd.c
clean:
	rm sachdeva_pa2_stra.exe sachdeva_pa2_tro.exe sachdeva_pa2_floyd.exe sachdeva_pa2_stra.o sachdeva_pa2_tro.o sachdeva_pa2_floyd.o
